on: [push]

name: CI

jobs:
    SpellCheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - uses: actions/checkout@v2
            - name: Install modules
              uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: Install dependencies
              run: pnpm install
            - name: Ensure Prettier was run
              run: pnpm spellcheck
    Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - uses: actions/checkout@v2
            - name: Install modules
              uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: Install vsce
              run: pnpm add -g @vscode/vsce
            - name: Install dependencies
              run: pnpm install
            - name: Package using webpack
              run: pnpm run package
    Lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - uses: actions/checkout@v2
            - name: Install modules
              uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: Install dependencies
              run: pnpm install
            - name: Run ESLint
              run: pnpm eslint src --ext ts
    Prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - uses: actions/checkout@v2
            - name: Install modules
              uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: Install dependencies
              run: pnpm install
            - name: Ensure Prettier was run
              run: pnpm prettier --check .
