on: [push]

name: CI

jobs:
    SpellCheck:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/setup-node@v3
          with:
            node-version: 16
        - uses: actions/checkout@v2
        - name: Install modules
          uses: bahmutov/npm-install@v1
        - name: Run cSpell
          run: yarn spellcheck