on: [push]

name: CI

jobs:
    SpellCheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - uses: actions/checkout@v2
            - name: Install modules
              uses: pnpm/action-setup@v2
              with:
                  version: 7
            - name: Install dependencies
              run: pnpm install
            - name: Run cSpell
              run: pnpm spellcheck
    Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - uses: actions/checkout@v2
            - name: Install modules
              uses: pnpm/action-setup@v2
              with:
                  version: 7
            - name: Install dependencies
              run: pnpm install
              run: pnpm add -g @vscode/vsce
            - name: Package using esbuild
              run: pnpm run package
    Lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - uses: actions/checkout@v2
            - name: Install modules
              uses: pnpm/action-setup@v2
              with:
                  version: 7
            - name: Install dependencies
              run: pnpm install
            - name: Run ESLint
              run: yarn eslint src --ext ts
    Prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - uses: actions/checkout@v2
            - name: Install modules
              uses: pnpm/action-setup@v2
              with:
                  version: 7
            - name: Install dependencies
              run: pnpm install
            - name: Ensure Prettier was run
              run: yarn prettier --check .
